{
 "title": "KVS WebRTC Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n  COUNT(DISTINCT ConnectionId) as ConnectionCount\nFROM $__database.$__table\nWHERE $__timeFilter\n"
    }
   ]
  },
  {
   "title": "Active User",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n  COUNT(DISTINCT UserId) AS ActiveUser\nFROM $__database.$__table\nWHERE $__timeFilter\n"
    }
   ]
  },
  {
   "title": "Network Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n    COUNT(DISTINCT ConnectionId) AS Cellular\nFROM $__database.$__table\nWHERE NetworkType = 'Cellular' AND $__timeFilter\n"
    },
    {
     "rawQuery": "SELECT\n    COUNT(DISTINCT ConnectionId) AS WIFI\nFROM $__database.$__table\nWHERE NetworkType = 'WIFI' AND $__timeFilter\n"
    }
   ]
  },
  {
   "title": "User Location Heatmap",
   "type": "geomap",
   "gridPos": { "h": 30, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawQuery": "SELECT\n  \"Latitude\" AS latitude,\n  \"Longitude\" AS longitue\nFROM $__database.$__table\nWHERE \"Latitude\" <> '0' OR \"Longitude\" <> '0' AND $__timeFilter\n"
    }
   ]
  },
  {
   "title": "KVS WebRTC Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawQuery": "SELECT\n\tSUM(CASE WHEN \"UseTurn\" = 'false' THEN 1 ELSE 0 END) OVER (ORDER BY time) AS P2P,\n\tSUM(CASE WHEN \"UseTurn\" = 'true' THEN 1 ELSE 0 END) OVER (ORDER BY time) AS Turn,\n\tSUM(CASE WHEN ConnectionId <> ' ' THEN 1 ELSE 0 END) OVER (ORDER BY time) AS Total,\n\ttime\nFROM $__database.$__table\nWHERE $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n"
    }
   ]
  },
  {
   "title": "Streaming Success Rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n    COUNT(CASE WHEN \"Streaming.RequestEndTime\" = '0' THEN \"Streaming.RequestEndTime\" END) AS Failed,\n    COUNT(CASE WHEN \"Streaming.RequestEndTime\" <> '0' THEN \"Streaming.RequestEndTime\" END) AS Success\nFROM $__database.$__table\nWHERE $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n"
    }
   ]
  },
  {
   "title": "Connections Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawQuery": "SELECT\n  DATE_TRUNC('hour', time) AS Time,\n  COUNT(DISTINCT ConnectionId) AS ConnectionCount\nFROM $__database.$__table\nWHERE $__timeFilter\nGROUP BY DATE_TRUNC('hour', time)\n"
    }
   ]
  },
  {
   "title": "P2P Rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n    COUNT(CASE WHEN \"UseTurn\" = 'false' THEN \"UseTurn\" END) AS P2P,\n    COUNT(CASE WHEN \"UseTurn\" = 'true' THEN \"UseTurn\" END) AS Relay\nFROM $__database.$__table\nWHERE $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n"
    }
   ]
  },
  {
   "title": "PreConnection Time Cost(Signaling)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawQuery": "SELECT\n  CAST(\"PreConnection.RequestEndTime\" AS double) - CAST(\"PreConnection.RequestStartTime\" AS double) AS PreConnectionTimeCost\nFROM $__database.$__table\nWHERE CAST(\"PreConnection.RequestEndTime\" AS double) - CAST(\"PreConnection.RequestStartTime\" AS double) < 15000 AND $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n"
    }
   ]
  },
  {
   "title": "Average PreConnection Time Cost(Signaling)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Streaming Time Cost",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawQuery": "SELECT\n  CAST(\"Streaming.RequestEndTime\" AS double) - CAST(\"Streaming.RequestStartTime\" AS double) AS StreamingTimeCost\nFROM $__database.$__table\nWHERE \"Streaming.RequestEndTime\" <> '0' AND $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n"
    }
   ]
  },
  {
   "title": "Average Streaming Time Cost(TTFF)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Streaming Time Cost(TTFF) Percentile",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n    APPROX_PERCENTILE(TimeCost, ARRAY[0.25,0.50,0.75,0.95]) as Percentiles\nFROM\n(\n    SELECT\n        CAST(\"Streaming.RequestEndTime\" AS double) - CAST(\"Streaming.RequestStartTime\" AS double) AS TimeCost\n    FROM\n        $__database.$__table\n    WHERE CAST(\"Streaming.RequestEndTime\" AS double) - CAST(\"Streaming.RequestStartTime\" AS double) > 0 AND $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\n)\n"
    }
   ]
  },
  {
   "title": "App Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n  AppVersion,\n  COUNT(*) AS Count\nFROM $__database.$__table\nWHERE $__timeFilter AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\nGROUP BY AppVersion\n"
    }
   ]
  },
  {
   "title": "Errors Percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT\n  COUNT(*) AS Count,\n  ErrorMessage\nFROM $__database.$__table\nWHERE $__timeFilter AND ErrorCode <> '0' AND (measure_name = 'API' OR measure_name = 'StreamingMetrics')\nGROUP BY ErrorCode, ErrorMessage\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 60 },
   "targets": [
    { "panelId": 34 }
   ]
  }
 ]
}